### ISSUE TITLE
vpc - ERROR: Unable to find RegKey for .vcproj or .vcxproj files in solutions.

### ISSUE THREAD

**Issue by garysplay** [EnderZip/cool-source#2]
I have VS 2022 / 2015 build tools and this error still comes

i have MFC for VS 2022

**Comment by EnderZip** [comment]
you need vs2013

**Comment by garysplay** [comment]
now it says 114 errors with both math.inl and math.h

**Comment by garysplay** [comment]
And now it says ThreadWaitForObjects could not be located in dll vphysics.dll 3 times

**Comment by garysplay** [comment]
why my resolution is 640x480 and all of vgui stuff is broken?

**Comment by EnderZip** [comment]
What branch are you using, if its dx11-win64 then its a normal thing for now since we haven't found a solution for that. If you are on win64 then i suggest recloning or pulling the repo, i've reverted some commits on that branch that i accidentally pushed

**Comment by garysplay** [comment]
alright also last question why my perfomance is quite low on 64bits?

**Comment by garysplay** [comment]
and vgui is still broken in that branch(

**Comment by EnderZip** [comment]
How low is the performance? Try net_graph 1 and send a screenshot here. Also send a vgui screenshot too

**Comment by garysplay** [comment]
Main Menu
![image](https://user-images.githubusercontent.com/27008012/179748887-8462fb3d-be59-418a-96b9-b9a6cf63af1c.png)
others are just white boxes

**Comment by garysplay** [comment]
i just copied HL2 retail files and unpacked vpk

**Comment by garysplay** [comment]
Console screen
![image](https://user-images.githubusercontent.com/27008012/179758050-d2347e50-4e93-4d4b-9028-f7c830df82d9.png)

**Comment by garysplay** [comment]
alright

**Comment by garysplay** [comment]
Now i encountered another bug(?) camera goes straight up and goes straight down when i turn to just look around

**Comment by EnderZip** [comment]
That's weird, try recording a video

**Comment by garysplay** [comment]
https://user-images.githubusercontent.com/27008012/179882552-c206c580-9550-4f63-9724-35ebf84027c4.mp4

**Comment by garysplay** [comment]
that's what happens when i turn mouse

**Comment by EnderZip** [comment]
What map is this?

**Comment by garysplay** [comment]
dz_blacksite (CSGO retail, BSP21)

**Comment by EnderZip** [comment]
mouse is fine for me, as for the low fps its because of the temporary broken bullet physics, when we got the real vphys working the fps will be better

**Comment by TheASVigilante** [comment]
@garysplay is you mouse sensitivity set correctly? Sometimes the engine sets a ridiculously high value which could cause this.

**Comment by garysplay** [comment]
how to check if my sens is too big?

**Comment by EnderZip** [comment]
Go to options->mouse

**Comment by garysplay** [comment]
Also a question: why does VBSP.exe does crash at this stack ?
uploaded mdmp file here
[vbsp_20220723_202009_1.zip](https://github.com/EnderZip/cool-source/files/9174263/vbsp_20220723_202009_1.zip)

**Comment by EnderZip** [comment]
Due to the broken vphys, you can't compile maps using coolsource tools yet

**Comment by EnderZip** [comment]
Closed due to inactivity
